var csvfile = [
  {
    "page": "Introduction",
    "number": 1,
    "description": "Welcome to the P5.js tutorial. Today you will be learning the three main functions provided by this powerful library. <br>",
    "task": "",
    "code": "",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Introduction",
    "number": 2,
    "description": "First, let's learn the basic structure of P5.js.<br>\nAs you can see from the code area. All the codes in this function will only be executed once when the code is loaded. ",
    "task": "",
    "code": "<b style=\"color:#265eb7\">function</b> setup() {<br>\n<br>\n}\n",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Introduction",
    "number": 3,
    "description": "\"createCanvas\" is a function from the P5.js library, which allows you to define a canvas with a specific width and height over the screen.<br>\nHowever, we defined the width and height here for you to fit the canvas window. Please do not modify these parameters.",
    "task": "",
    "code": "<b style=\"color:#265eb7\">function</b> setup() {<br>\n&nbsp;&nbsp;createCanvas(width, height);<br>\n}\n",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Introduction",
    "number": 4,
    "description": "All the codes in this function will be executed repeatedly. ",
    "task": "",
    "code": "<b style=\"color:#265eb7\">function</b> draw() {<br>\n  <br>\n\n}",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Introduction",
    "number": 5,
    "description": "\"background\" defines the color of the current Canvas you created. <br>\n",
    "task": "Now, please try to change 0 to another different value between 0 to 255. And then click \"Run\".",
    "code": "<b style=\"color:#265eb7\">function</b> draw() {<br>\n    &nbsp;&nbsp;background(0);<br>\n\n}",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Shape and Color",
    "number": 1,
    "description": "Your first task will be creating different shapes on the graph.<br>\nTo create a shape, you should first specify the color of the shape. Here, we've provide you with a rectangle, but it has a default color.<br>\nUse this function to set the color used to fill shapes. For example, if you run fill(204, 102, 0), all subsequent shapes will be filled with orange.",
    "task": "Please set the color to:<br>\nred = 250 <br>\ngreen = 60 <br>\nblue = 60 <br>",
    "code": "fill(r, g, b);",
    "feedback": "Did you write the code in the \"draw\" function?",
    "hint_1": "red corresponds to the first parameter.<br>\ngreen corresponds to the second parameter.<br>\nblue corresponds to the thrid parameter.",
    "hint_2": "fill(250,60,60);",
    "answer_1": "fill(250,60,60)",
    "answer_2": "",
    "reset": "shape1"
  },
  {
    "page": "Shape and Color",
    "number": 2,
    "description": "Now you have successfully set the color, you can now draw the shapes on canvas.<br>\nUse the following function to draw a rectangle to the screen. A rectangle is a four-sided shape with every angle at ninety degrees. <br>By default, the first two parameters set the location of the upper-left corner, the third sets the width, and the fourth sets the height.",
    "task": "Please add a rectangle with height 40 and width 30 at location (100,200).",
    "code": "rect(x, y, w, h);",
    "feedback": "Make sure you understand the meaning of each parameter in this function.",
    "hint_1": "Use the formlua provided and fill in the four parameters as described by the task.",
    "hint_2": "rect(100,200,30,40);",
    "answer_1": "rect(100,200,30,40)",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Shape and Color",
    "number": 3,
    "description": "Now Let's try a different color!<br>\nLet's set the color first. Use the function below again.",
    "task": "Please set the color to:<br>\nred = 60 <br>\ngreen = 90 <br>\nblue = 200 <br>",
    "code": "fill(r, g, b);",
    "feedback": "Did you overwrite the previous code?",
    "hint_1": "red corresponds to the first parameter.<br>\ngreen corresponds to the second parameter.<br>\nblue corresponds to the thrid parameter.",
    "hint_2": "fill(60, 90, 200);",
    "answer_1": "fill(60,90,200)",
    "answer_2": "",
    "reset": "reset"
  },
  {
    "page": "Shape and Color",
    "number": 4,
    "description": "This function will draw an ellipse (oval) to the screen. An ellipse with equal width and height is a circle. <br>By default, the first two parameters set the location, and the third and fourth parameters set the shape's width and height. If no height is specified, the value of width is used for both the width and height. If a negative height or width is specified, the absolute value is taken.",
    "task": "Please draw a circle with width (diameter) 40 at location (50,50).",
    "code": "ellipse(x, y, w, h);",
    "feedback": "Make sure you understand the meaning of each parameter in this function.",
    "hint_1": "Use the formlua provided and fill in the four parameters as described by the task.",
    "hint_2": "ellipse(50,50,40,40);",
    "answer_1": "ellipse(50,50,40,40)",
    "answer_2": "ellipse(50,50,40)",
    "reset": ""
  },
  {
    "page": "Motion",
    "number": 1,
    "description": "Now Let's learn a new effect that P5.js provides.<br>\nWe can not only draw still images over a screen. We can also make an object move.<br>\nHere we provide you a basic structure of an object and it's position prefined.<br>\nThese two values define the x position and y position of an object.",
    "task": "",
    "code": "<b style=\"color:#265eb7\">var</b> x; <br>\n<b style=\"color:#265eb7\">var</b> y; <br>\n",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": "motion1"
  },
  {
    "page": "Motion",
    "number": 2,
    "description": "In function \"setup()\", we defined the initial value of the x and y position of this object.<br>\n*Note: In P5.js, width and height are two pre-defined constant value which represents the width and height of the canvas.",
    "task": "",
    "code": "  x = width / 2;<br>\n  y = height - 10;",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Motion",
    "number": 3,
    "description": "In function \"draw()\", we defined our object - a circle with position x and y and radius 50.",
    "task": "",
    "code": "fill(100); <br>\nellipse(x, y, 50, 50);",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Motion",
    "number": 4,
    "description": "In our current code segment. We did not change the value of x and y everytime we execute \"draw()\".<br>\nHowever, we can change their value to make the object move!",
    "task": "Please try to modify the y position to make the circle moving up 1 pixel every time the function \"draw()\" is executed.",
    "code": "x = x; <br>\ny = y;",
    "feedback": "",
    "hint_1": "To move the circle up, you should decrease the value of y until it reaches 0.",
    "hint_2": "y = y - 1;",
    "answer_1": "y=y-1",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Motion",
    "number": 5,
    "description": "Now let's try something harder!<br>\nWe would like to utilize the random function to change the x position of the circle.",
    "task": "Please modify the x position to make the ball moving left and right randomly within -1 and 1 each iteration the function \"draw()\" is executed.",
    "code": "random([min],[max]);",
    "feedback": "",
    "hint_1": "The random function will generate a random floating-point number between the two parameters.",
    "hint_2": "x = x + random(-1,1);",
    "answer_1": "x=x+random(-1,1)",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Interaction",
    "number": 1,
    "description": "Now, here's the final powerful module that P5.js provides. <br>\nFirst, we pre-defined a circle in the middle of the screen with a diameter of 50.",
    "task": "",
    "code": "<b style=\"color:#265eb7\">var</b> x; <br>\n<b style=\"color:#265eb7\">var</b> y; <br>\n<b style=\"color:#265eb7\">var</b> r; <br>\nx = width/2; <br>\ny = height/2; <br>\nr = 50; <br>",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": "interaction1"
  },
  {
    "page": "Interaction",
    "number": 2,
    "description": "This <b>if-statement</b> needs to be modified to achieve interaction - so when we hover the index over the circle, the circle will tickle (moving randomly)",
    "task": "",
    "code": "if(<b style=\"color:#36047c\">false,</b>){ <br>\n&nbsp;&nbsp;x += random(-1, 1);<br>\n&nbsp;&nbsp;y += random(-1, 1);<br>\n}",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Interaction",
    "number": 3,
    "description": "P5.js library provides us with the ease to listen to the position of our index. <br>\nSo we can easily detect if we have hovered the mouse over an object as long as we have<br>\n&nbsp&nbsp- the x and y position of an object <br>\n&nbsp&nbsp- the x and y position of our index <br>",
    "task": "Please replace the false in the if-statement to <br>\nmouseX >= x - r/2 && mouseX <= x + r/2",
    "code": "mouseX <br>",
    "feedback": "",
    "hint_1": "Just copy and paste the code!",
    "hint_2": "mouseX >= x - r/2 && mouseX <= x + r/2",
    "answer_1": "mouseX>=x-r/2&&mouseX<=x+r/2",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Interaction",
    "number": 4,
    "description": "Now, hover your mouse over the circle.<br>\nThe circle is tickling! However, since we haven't detect the y position, the circle will still tickle even we hover the mouse above or below it. ",
    "task": "Please refine mouseY (the y position of your index) like what we just did for mouseX in the if-statement.",
    "code": "mouseY <br>",
    "feedback": "",
    "hint_1": "Since the object is a circle, the detection for mouseY should be exactly the same as for mouseX",
    "hint_2": "mouseY >= y - r/2 && mouseY <= y + r/2",
    "answer_1": "mouseX>=x-r/2&&mouseX<=x+r/2&&mouseY>=y-r/2&&mouseY<=y+r/2",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Follow",
    "number": 1,
    "description": "Here's the final toturial. And it is also the most complext part.<br>\nFor this section, you don't need to fully undersand how each line of code works. However, you need to understand the meaning of each function.",
    "task": "Try to move around your mouse on the canvas.",
    "code": "",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": "follow1"
  },
  {
    "page": "Follow",
    "number": 2,
    "description": "The code in function \"draw()\" calculate the position of the line and the angle that the line should incline.",
    "task": "",
    "code": "<b style=\"color:#265eb7\">function</b>  draw() {<br>\n &nbsp;&nbsp;background(0);<br>\n &nbsp;&nbsp; dx = mouseX - x;<br>\n &nbsp;&nbsp; dy = mouseY - y;<br>\n &nbsp;&nbsp; angle1 = atan2(dy, dx);<br>\n &nbsp;&nbsp; x = mouseX - (cos(angle1) * segLength);<br>\n  &nbsp;&nbsp;y = mouseY - (sin(angle1) * segLength);<br>\n &nbsp;&nbsp; segment(x, y, angle1);<br>\n}",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Follow",
    "number": 3,
    "description": "The code in function \"segment()\" draws the line. <br>\nHowever, currently, we just keep drawing the line at position (0,0) which doesn't make sense.",
    "task": "",
    "code": "<b style=\"color:#265eb7\">function</b> segment() {<br>\n  &nbsp;&nbsp; push();\n  &nbsp;&nbsp; line(0, 0, segLength, 0);\n  &nbsp;&nbsp; pop();\n}",
    "feedback": "",
    "hint_1": "",
    "hint_2": "",
    "answer_1": "",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Follow",
    "number": 4,
    "description": "To move an object, we have two ways to achieve it:<br>\n&nbsp;&nbsp; - change the x and y position of the object<br>\n&nbsp;&nbsp; - use the \"translate()\" function:\nThis function specifies an amount to displace objects within the display window. The x parameter specifies left/right translation, the y parameter specifies up/down translation. <br>\nTransformations are cumulative and apply to everything that happens after and subsequent calls to the function accumulates the effect. For example, calling translate(50, 0) and then translate(20, 0) is the same as translate(70, 0). <b> *Note: If translate() is called within draw(), the transformation is reset when the loop begins again</b>. This function can be further controlled by using push() and pop().",
    "task": "Please add  translate to function \"segment()\" using the parameters provided.",
    "code": "translate(x, y);",
    "feedback": "",
    "hint_1": "translate(x, y);",
    "hint_2": "translate(x, y);",
    "answer_1": "translate(x,y)",
    "answer_2": "",
    "reset": ""
  },
  {
    "page": "Follow",
    "number": 5,
    "description": "Now, the objects can follow our index!<br>\nHowever, we need to utilize the rotation, otherwise the line will only be horizontal!<br>\nThe function below rotates a shape the amount specified by the angle parameter.",
    "task": "Please add  rotation to function \"segment()\" using the parameters provided.",
    "code": "rotate(angle);",
    "feedback": "",
    "hint_1": "rotate(a);",
    "hint_2": "rotate(a);",
    "answer_1": "rotate(a)",
    "answer_2": "",
    "reset": ""
  }
];