var csvfile = [
    {
      "page": "Introduction",
      "number": 1,
      "description": "Welcome to the P5.js tutorial. Today you will be learning the three main functions provided by this powerful library. <br>",
      "task": "",
      "code": "",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Introduction",
      "number": 2,
      "description": "First, let's learn the basic structure of P5.js.<br>\nAs you can see from the code area. All the codes in this function will only be executed once when the code is loaded. ",
      "task": "",
      "code": "<b style=\"color:#265eb7\">function</b> setup() {<br>\n<br>\n}\n",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Introduction",
      "number": 3,
      "description": "\"createCanvas\" is a function from the P5.js library, which allows you to define a canvas with a specific width and height over the screen.<br>\nHowever, we defined the width and height here for you to fit the canvas window. Please do not modify these parameters.",
      "task": "",
      "code": "<b style=\"color:#265eb7\">function</b> setup() {<br>\n&nbsp;&nbsp;createCanvas(width, height);<br>\n}\n",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Introduction",
      "number": 4,
      "description": "All the codes in this function will be executed repeatedly. ",
      "task": "",
      "code": "<b style=\"color:#265eb7\">function</b> draw() {<br>\n  <br>\n\n}",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Introduction",
      "number": 5,
      "description": "\"background\" defines the color of the current Canvas you created. <br>\n",
      "task": "Now, please try to change 0 to another different value between 0 to 255. And then click \"Run\".",
      "code": "<b style=\"color:#265eb7\">function</b> draw() {<br>\n    &nbsp;&nbsp;background(0);<br>\n\n}",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Shape and Color",
      "number": 1,
      "description": "Your first task will be creating different shapes on the graph.<br>\nTo create a shape, you should first specify the color of the shape. Here, we've provide you with a rectangle, but it has a default color.<br>\nUse this function to set the color used to fill shapes. For example, if you run fill(204, 102, 0), all subsequent shapes will be filled with orange.",
      "task": "Please set the color to:<br>\nred = 250 <br>\ngreen = 60 <br>\nblue = 60 <br>",
      "code": "fill(r, g, b);",
      "feedback": "Did you write the code in the \"draw\" function?",
      "hint_1": "red corresponds to the first parameter.<br>\ngreen corresponds to the second parameter.<br>\nblue corresponds to the thrid parameter.",
      "hint_2": "fill(250,60,60);",
      "answer_1": "fill(250,60,60)",
      "answer_2": "",
      "reset": "shape1"
    },
    {
      "page": "Shape and Color",
      "number": 2,
      "description": "Now you have successfully set the color, you can now draw the shapes on canvas.<br>\nUse the following function to draw a rectangle to the screen. A rectangle is a four-sided shape with every angle at ninety degrees. <br>By default, the first two parameters set the location of the upper-left corner, the third sets the width, and the fourth sets the height.",
      "task": "Please add a rectangle with height 40 and width 30 at location (100,200).",
      "code": "rect(x, y, w, h);",
      "feedback": "Make sure you understand the meaning of each parameter in this function.",
      "hint_1": "Use the formlua provided and fill in the four parameters as described by the task.",
      "hint_2": "rect(100,200,30,40);",
      "answer_1": "rect(100,200,30,40)",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Shape and Color",
      "number": 3,
      "description": "Now Let's try a different color!<br>\nUse the function below again.",
      "task": "Please set the color to:<br>\nred = 60 <br>\ngreen = 90 <br>\nblue = 200 <br>",
      "code": "fill(r, g, b);",
      "feedback": "Did you overwrite the previous code?",
      "hint_1": "red corresponds to the first parameter.<br>\ngreen corresponds to the second parameter.<br>\nblue corresponds to the thrid parameter.",
      "hint_2": "fill(60, 90, 200);",
      "answer_1": "fill(60,90,200)",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Shape and Color",
      "number": 4,
      "description": "This function will draw an ellipse (oval) to the screen. An ellipse with equal width and height is a circle. <br>By default, the first two parameters set the location, and the third and fourth parameters set the shape's width and height. If no height is specified, the value of width is used for both the width and height. If a negative height or width is specified, the absolute value is taken.",
      "task": "Please draw a circle with radius 40 at location (50,50).",
      "code": "ellipse(x, y, w, h);",
      "feedback": "Make sure you understand the meaning of each parameter in this function.",
      "hint_1": "Use the formlua provided and fill in the four parameters as described by the task.",
      "hint_2": "ellipse(50,50,40,40);",
      "answer_1": "ellipse(50,50,40,40)",
      "answer_2": "ellipse(50,50,40)",
      "reset": ""
    },
    {
      "page": "Motion",
      "number": 1,
      "description": "Now Let's learn a new effect that P5.js provides.<br>\nWe can not only draw still images over a screen. We can also make an object move.<br>\nHere we provide you a basic structure of an object and it's position prefined.<br>\nThese two values define the x position and y position of an object.",
      "task": "",
      "code": "<b style=\"color:#265eb7\">var</b> x; <br>\n<b style=\"color:#265eb7\">var</b> y; <br>\n",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": "motion1"
    },
    {
      "page": "Motion",
      "number": 2,
      "description": "In function \"setup()\", we defined the initial value of the x and y position of this object.<br>\n*Note: In P5.js, width and height are two pre-defined constant value which represents the width and height of the canvas.",
      "task": "",
      "code": "  x = width / 2;<br>\n  y = height - 10;",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Motion",
      "number": 3,
      "description": "In function \"draw()\", we defined our object - a circle with position x and y and radius 50.",
      "task": "",
      "code": "fill(100); <br>\nellipse(x, y, 50, 50);",
      "feedback": "",
      "hint_1": "",
      "hint_2": "",
      "answer_1": "",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Motion",
      "number": 4,
      "description": "In our current code segment. We did not change the value of x and y everytime we execute \"draw()\".<br>\nHowever, we can change their value to make the object move!",
      "task": "Please try to modify the y position to make the circle moving up 1 pixel every time the function \"draw()\" is executed.",
      "code": "x = x; <br>\ny = y;",
      "feedback": "",
      "hint_1": "To move the circle up, you should decrease the value of y until it reaches 0.",
      "hint_2": "y = y - 1;",
      "answer_1": "y=y-1",
      "answer_2": "",
      "reset": ""
    },
    {
      "page": "Motion",
      "number": 5,
      "description": "Now let's try something harder!<br>\nWe would like to utilize the random function to change the x position of the circle.",
      "task": "Please modify the x position to make the ball moving left and right randomly within -1 and 1 each iteration the function \"draw()\" is executed.",
      "code": "random([min],[max]);",
      "feedback": "",
      "hint_1": "",
      "hint_2": "x = x + random(-1,1);",
      "answer_1": "x=x+random(-1,1)",
      "answer_2": "",
      "reset": ""
    }
   ];